In [47]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier

In [48]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [49]:
def transformar_sexo(valor):
    if valor == 'female':
        return 1
    else:
        return 0

In [50]:
train['Sex_binario'] = train['Sex'].map(transformar_sexo)
test['Sex_binario'] = test['Sex'].map(transformar_sexo)

In [51]:
variaveis = ['Sex_binario', 'Age']

In [52]:
X_train = train[variaveis].fillna(-1)
y_train = train['Survived']

In [53]:
modelo = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=0)
modelo.fit(X_train, y_train)

RandomForestClassifier(n_jobs=-1, random_state=0)

In [54]:
X_test = test[variaveis].fillna(-1)
predictions = modelo.predict(X_test)

In [55]:
test['Survived'] = predictions

In [64]:
predictions_series = pd.Series(predictions, index=test['PassengerId'], name='Survived')
predictions_series.to_csv("primeiro_modelo.csv", header=True)

In [65]:
styled = test.style.applymap(
    lambda x: 'background-color: lightgreen' if x == 1 else '',
    subset=['Survived']
)

styled = styled.set_properties(**{
    'background-color': 'lightgray',
    'color': 'black',
    'border-color': 'gray'
})

In [68]:
styled